name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os:
          - blacksmith
          - macos-latest
        go:
          - '1.21'
          - '1.22'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - run: go test -v -tags swiss_invariants

  linux-race:
    name: go-linux-race
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: useblacksmith/setup-go@v6
        with:
          go-version: "1.22"

      - run: go test -v -race

  linux-32bit:
    name: go-linux-32bit
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: useblacksmith/setup-go@v6
        with:
          go-version: "1.22"

      - run: GOARCH=386 go test -v -tags swiss_invariants
